### PR TITLE
Adds Swift 2.2 support

### PR DESCRIPTION
**Pull request by ikovalisko**
Just adopted new fancy `#selector` syntax.

### CODE REVIEW

**Comment by marcelofabri** [comment]
@ikovalisko Would you mind updating the `xcodebuild` in `.travis.yml` to use the 9.3 simulator so the build can pass?

**Comment by ikovalisko** [comment]
@marcelofabri done.

I just thought that this PR drops support for Swift **pre 2.2**. New selector syntax is not backward compatible. Are you OK with that?

**Comment by marcelofabri** [comment]
Yeah, people using older versions of Swift can always lock to older versions of the library.

Thanks for doing this! 🎉

**Comment by marcelofabri** [comment]
@ikovalisko Just released 0.4.0. Thanks again 💯

**Comment by ikovalisko** [comment]
👍

**Pull request merged**
